<a href="https://colab.research.google.com/github/Awan2001/DSC650---Group-Project-Dataset-Transform-/blob/main/DSC650_6A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div style="background-color: #f0f0f0; padding: 10px; border-radius: 5px;">
    <h2 style="color: #333;">Perform Transformation</h2>
    <p style="font-style: italic;">This section focuses on data transformation steps.</p>
</div>

## Import libraries

In [ ]:
# prompt: mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Import libraries

In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np

## Load dataset

In [ ]:
# Load datasets in format CSV
file_path_restos = '/content/drive/MyDrive/project_dataset/sg_restos.csv'
file_path_reviews = '/content/drive/MyDrive/project_dataset/sg_reviews.csv'

df_restos = pd.read_csv(file_path_restos)
df_reviews = pd.read_csv(file_path_reviews)

## Preview dataset

In [ ]:
# Display both df info
print("First df : Restos")
print("-" * 50)
df_restos.info()
print("=" * 50 + "\n\n")

print("Second df : Reviews")
print("-" * 50)
df_reviews.info()
print("=" * 50)

First df : Restos
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5649 entries, 0 to 5648
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StoreId            5649 non-null   object
 1   CompleteStoreName  5649 non-null   object
 2   FoodType           5649 non-null   object
 3   AverageRating      5649 non-null   float64
 4   Reviewers          5649 non-null   object
 5   City               5649 non-null   object
 6   Location           0 non-null      float64
dtypes: float64(2), object(5)
memory usage: 309.1+ KB
==================================================


Second df : Reviews
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76213 entries, 0 to 76212
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   StoreId          76213 non-null  object
 1   uuid             76213 non-null  object
 2   createdAt        76213 non-null  object
 3   updatedAt        76213 non-null  object
 4   text             76213 non-null  object
 5   isAnonymous      76213 non-null  bool
 6   reviewerId       76213 non-null  object
 7   replies          76213 non-null  object
 8   likeCount        76213 non-null  float64
 9   isLiked          76213 non-null  bool
 10  overall          76213 non-null  int64
 11  restaurant_food  76213 non-null  int64
 12  rider            29760 non-null  float64
dtypes: bool(2), float64(2), int64(2), object(7)
memory usage: 6.5+ MB
==================================================

In [ ]:
# Display first 10 rows for both df
print("First df : Restos")
display(df_restos.head(10))
print("=" * 100 + "\n\n")

print("Second df : Reviews")
display(df_reviews.head(10))
print("=" * 125)

First df : Restos

,StoreId,CompleteStoreName,FoodType,AverageRating,Reviewers,City,Location
0,sos6,Teochew Hai Gang Fish Soup 潮州海港鱼汤 (Toa Payoh),Asian,4.0,(1),Singapore,NaN
1,cc4y,Homtang Thai (Balestier Road),Thai,4.9,(9),Singapore,NaN
2,sh3w,Xin Mei Xiang Zheng Zong Lor Mee 新美香正宗卤面 (Bale...,Noodles,4.4,(100+),Singapore,NaN
3,ih76,Soon Huat BBQ Seafood (Lorong 4 Toa Payoh),Seafood,4.3,(100+),Singapore,NaN
4,yrj9,BaliNice Mala Hotpot 八里香麻辣香锅 (Lorong 1 Toa Payoh),Snacks,4.2,(89),Singapore,NaN
5,s1jq,Shi Kou Seafood (Balestier Road),Chinese,4.3,(500+),Singapore,NaN
6,c8dk,Tea Apothecary (Toa Payoh View),Bubble Tea,4.7,(100+),Singapore,NaN
7,x7gm,Xiao Lao Ban Xiang Guo 小老板香锅 (Balestier Road),Curry,4.1,(100+),Singapore,NaN
8,x2ku,Thai Tai 泰太 (Former Noodle ThaiThai),Thai,4.7,(3000+),Singapore,NaN
9,h6sj,Fire Rice (125 Toa Payoh Lorong),Fried Rice,4.9,(13),Singapore,NaN

====================================================================================================


Second df : Reviews

,StoreId,uuid,createdAt,updatedAt,text,isAnonymous,reviewerId,replies,likeCount,isLiked,overall,restaurant_food,rider
0,y7bj,00024132-6b31-4116-8e58-4e81599b78b7,2024-02-18T10:25:27Z,2024-02-18T10:25:27Z,Ordered Samosa and Vadai as we wanted for snac...,False,sghsi8yy,[],0.0,False,1,1,5.0
1,fnna,0002e806-35d5-4907-bb3a-75cbaef3a6e0,2023-04-03T11:12:11Z,2023-04-03T11:12:11Z,food is nice but portion small.,False,b1avz0td,[],0.0,False,5,5,5.0
2,kfgv,000317da-02fb-49b1-a667-8167d91105a5,2023-11-03T10:44:38Z,2023-11-03T10:44:38Z,"I ordered 2 items, only 1 delivered. but I was...",False,r8oii2qv,[],0.0,False,1,1,NaN
3,y8nn,0005a46a-a540-427e-9133-793b1e0ab9c0,2023-09-25T12:36:18Z,2023-09-25T12:36:18Z,I order 6 seaweed chicken but they gave 2,False,sgnuk7bx,[],0.0,False,1,1,NaN
4,zu87,0006e092-5cdb-40e9-b6a4-6f01dbca991c,2023-09-10T10:29:49Z,2023-09-10T10:29:49Z,Good as usual...,False,p2zyj8px,[],0.0,False,5,5,NaN
5,zhaf,0007d0b5-7c84-4192-8012-3e126156ab7a,2023-04-30T09:57:14Z,2023-04-30T09:57:14Z,The portions were smaller than expected.,False,g1pav7ov,[],0.0,False,3,3,5.0
6,w5ou,00088c6a-fbc3-41b5-b695-3eb8639a6800,2023-06-25T09:44:34Z,2023-06-25T09:44:34Z,Not spicy enough. Soup not tasty. Quantity of ...,False,g8yot4nl,[],0.0,False,4,4,NaN
7,c3wp,0009176c-d7d1-4fe5-badb-0f014862f23f,2023-04-29T02:48:26Z,2023-04-29T02:48:26Z,Flavorful pastas with affordable prices.,False,sgqfg69a,[],0.0,False,5,5,NaN
8,v8jb,000a26c0-9f62-464c-9d04-61dce2c91a29,2023-04-09T12:03:00Z,2023-04-09T12:03:00Z,food is not bad but there was a missing item w...,False,p3ptl9nz,[],0.0,False,3,3,5.0
9,w0wv,000bfbdf-3497-40a2-99f3-666f3ec910a8,2023-04-12T05:06:10Z,2023-04-12T05:06:10Z,"ordered set..but order came without drink, dis...",False,q9duu1ah,[],0.0,False,1,1,4.0

=============================================================================================================================

In [ ]:
# Display last 10 rows for both df
print("First df : Restos")
display(df_restos.tail(10))
print("=" * 100 + "\n\n")

print("Second df : Reviews")
display(df_reviews.tail(10))
print("=" * 125)

First df : Restos

,StoreId,CompleteStoreName,FoodType,AverageRating,Reviewers,City,Location
5639,rhp2,ANDES by ASTONS (Changi Village),Grill,4.9,(62),Singapore,NaN
5640,gjyu,DLLM Lok Lok (511 Upper Jurong),Malaysian,4.5,(100+),Singapore,NaN
5641,w1jq,1983 Coffee & Toast (Joo Koon),Coffee,4.6,(1000+),Singapore,NaN
5642,zvko,Douraku Sushi (Upper Jurong),Sushi,3.4,(7),Singapore,NaN
5643,jxjl,The Soup Spoon Union (NTU),Soups,5.0,(23),Singapore,NaN
5644,le9p,Jeukseok Town (5 Changi Village Road),Korean,1.7,(3),Singapore,NaN
5645,edm5,Billy & Brothers House Of Noodles (Loyang Way),Laksa,4.0,(32),Singapore,NaN
5646,h7jv,Frozen Heart Fried Ice Cream (Jewel),Ice Cream,5.0,(1),Singapore,NaN
5647,akmd,Jetaway Foodhub (Changi Village),Nasi Lemak,4.5,(77),Singapore,NaN
5648,kq3o,Claypot Little Brother砂煲小弟 (41 Joo Koon),Chinese,4.4,(14),Singapore,NaN

====================================================================================================


Second df : Reviews

,StoreId,uuid,createdAt,updatedAt,text,isAnonymous,reviewerId,replies,likeCount,isLiked,overall,restaurant_food,rider
76203,mgsf,fffab6f4-f7a5-45f3-83c7-47f283650ab2,2024-01-19T12:58:47Z,2024-01-19T12:58:47Z,Pathetic portion for a $18 petai with prawns. ...,False,j3lsl0fl,[],0.0,False,1,1,NaN
76204,uuz3,fffad1f0-fbd1-43f6-afc8-b5d1bedb7f99,2023-12-18T05:23:16Z,2023-12-18T05:23:16Z,Missing meat from my order,False,sgstwtc7,[],0.0,False,1,1,NaN
76205,y8cy,fffb024a-29cc-4855-baac-62acaf0a7829,2023-10-10T04:14:03Z,2023-10-10T04:14:03Z,The Chicken Cutlet Rice is really really delic...,False,t2giv2fj,[],0.0,False,5,5,NaN
76206,v0zp,fffc2246-7277-49a0-a1ba-e25ce7c74e48,2023-11-20T05:29:14Z,2023-11-20T05:29:14Z,The satay too crispy and hard.The lontong very...,False,sgz84r0x,[],0.0,False,1,1,NaN
76207,k9fv,fffdc32a-b7c7-44f2-b2bb-30b1755ff2f9,2023-12-10T13:48:16Z,2023-12-10T13:48:16Z,Wrong items gave,False,sgxrrlr1,[],0.0,False,1,1,NaN
76208,h2mc,fffe3b18-13ad-4eb4-b1a6-9d7ee10acff8,2024-02-17T04:21:48Z,2024-02-17T04:21:48Z,Sauce shld have separated . All meats become s...,False,sggqw5cy,[],0.0,False,4,4,NaN
76209,scg5,fffeb6c8-c0f6-4181-af3e-118686c5e3ac,2023-12-28T21:27:45Z,2023-12-28T21:27:45Z,Misiing item! TAT,False,sgtd8e12,[],0.0,False,1,1,NaN
76210,yvv4,ffff0ffc-d52b-4146-819a-26aae12a54a0,2023-08-02T13:42:45Z,2023-08-02T13:42:45Z,One of the best western food u guys should try...,False,sgqm95at,[],0.0,False,5,5,5.0
76211,s8ld,ffff2132-b778-4cef-99b4-5482669bc6f4,2023-05-16T02:37:35Z,2023-05-16T02:37:35Z,Delicious vegan food :),False,sgiowaje,[],0.0,False,5,5,5.0
76212,chke,ffffd9cb-5c7c-4f11-ae85-f88d59bda3b7,2023-06-21T08:43:28Z,2023-06-21T08:43:28Z,Ordered many times cause i love food. Nice sam...,False,i1wnw5xi,[],0.0,False,5,5,5.0

=============================================================================================================================

## Drop unnecessary columns

In [ ]:
# Remove columns that are useless for analysis

# Columns from df_restos
print("First df : Restos")
columns_to_drop_restos = ['Location']
for column in columns_to_drop_restos:
    if column in df_restos.columns:
        df_restos = df_restos.drop(columns=[column])
        print(f"Reason for removal :\n- '{column}' : Contains 100% null values.")
    else:
        print(f"You are trying to remove non-existent column : '{column}'")
display(df_restos.head(10))
print("=" * 100 + "\n\n")

# Columns from df_reviews
print("Second df : Reviews")
columns_to_drop_reviews = ['uuid', 'createdAt', 'updatedAt', 'replies', 'overall']
reasons_for_removal = {
    'uuid': "Unique ID (PK) for reference already exists which is the 'StoreId' in both df.",
    'createdAt': "Queries using these columns are less meaningful.",
    'updatedAt': "Queries using these columns are less meaningful.",
    'replies': "Values are too complex and is a short paragraph.",
    'overall': "Values are duplicates from column 'restaurant_food'. 'rider' is an independent column for rating of the delivery person hence not associated with the 'overall' rating as it should."
}
removal_reasons = []
nonexistent_columns = []
for column in columns_to_drop_reviews:
    if column in df_reviews.columns:
        df_reviews = df_reviews.drop(columns=[column])
        removal_reasons.append(f"- '{column}' : {reasons_for_removal[column]}")
    else:
        nonexistent_columns.append(f"'{column}'")
if nonexistent_columns:
    print(f"You are trying to remove non-existent column : {', '.join(nonexistent_columns)}")
if removal_reasons:
    print("Reason for removal :")
    print("\n".join(removal_reasons))
display(df_reviews.head(10))
print("=" * 100)

First df : Restos
Reason for removal :
- 'Location' : Contains 100% null values.

,StoreId,CompleteStoreName,FoodType,AverageRating,Reviewers,City
0,sos6,Teochew Hai Gang Fish Soup 潮州海港鱼汤 (Toa Payoh),Asian,4.0,(1),Singapore
1,cc4y,Homtang Thai (Balestier Road),Thai,4.9,(9),Singapore
2,sh3w,Xin Mei Xiang Zheng Zong Lor Mee 新美香正宗卤面 (Bale...,Noodles,4.4,(100+),Singapore
3,ih76,Soon Huat BBQ Seafood (Lorong 4 Toa Payoh),Seafood,4.3,(100+),Singapore
4,yrj9,BaliNice Mala Hotpot 八里香麻辣香锅 (Lorong 1 Toa Payoh),Snacks,4.2,(89),Singapore
5,s1jq,Shi Kou Seafood (Balestier Road),Chinese,4.3,(500+),Singapore
6,c8dk,Tea Apothecary (Toa Payoh View),Bubble Tea,4.7,(100+),Singapore
7,x7gm,Xiao Lao Ban Xiang Guo 小老板香锅 (Balestier Road),Curry,4.1,(100+),Singapore
8,x2ku,Thai Tai 泰太 (Former Noodle ThaiThai),Thai,4.7,(3000+),Singapore
9,h6sj,Fire Rice (125 Toa Payoh Lorong),Fried Rice,4.9,(13),Singapore

====================================================================================================


Second df : Reviews
Reason for removal :
- 'uuid' : Unique ID (PK) for reference already exists which is the 'StoreId' in both df.
- 'createdAt' : Queries using these columns are less meaningful.
- 'updatedAt' : Queries using these columns are less meaningful.
- 'replies' : Values are too complex and is a short paragraph.
- 'overall' : Values are duplicates from column 'restaurant_food'. 'rider' is an independent column for rating of the delivery person hence not associated with the 'overall' rating as it should.

,StoreId,text,isAnonymous,reviewerId,likeCount,isLiked,restaurant_food,rider
0,y7bj,Ordered Samosa and Vadai as we wanted for snac...,False,sghsi8yy,0.0,False,1,5.0
1,fnna,food is nice but portion small.,False,b1avz0td,0.0,False,5,5.0
2,kfgv,"I ordered 2 items, only 1 delivered. but I was...",False,r8oii2qv,0.0,False,1,NaN
3,y8nn,I order 6 seaweed chicken but they gave 2,False,sgnuk7bx,0.0,False,1,NaN
4,zu87,Good as usual...,False,p2zyj8px,0.0,False,5,NaN
5,zhaf,The portions were smaller than expected.,False,g1pav7ov,0.0,False,3,5.0
6,w5ou,Not spicy enough. Soup not tasty. Quantity of ...,False,g8yot4nl,0.0,False,4,NaN
7,c3wp,Flavorful pastas with affordable prices.,False,sgqfg69a,0.0,False,5,NaN
8,v8jb,food is not bad but there was a missing item w...,False,p3ptl9nz,0.0,False,3,5.0
9,w0wv,"ordered set..but order came without drink, dis...",False,q9duu1ah,0.0,False,1,4.0

====================================================================================================

### Due to the text column contain commas and other unique symbol make this hard to analysis. Thefore, it is better to drop this column.

In [ ]:
# prompt: drop text column from df_reviews

# Drop the 'text' column from df_reviews
df_reviews = df_reviews.drop(columns=['text'])

# Display the first 10 rows of the updated df_reviews
display(df_reviews.head(10))

  StoreId  isAnonymous reviewerId  likeCount  isLiked  restaurant_food  rider
0    y7bj        False   sghsi8yy        0.0    False                1    5.0
1    fnna        False   b1avz0td        0.0    False                5    5.0
2    kfgv        False   r8oii2qv        0.0    False                1    NaN
3    y8nn        False   sgnuk7bx        0.0    False                1    NaN
4    zu87        False   p2zyj8px        0.0    False                5    NaN
5    zhaf        False   g1pav7ov        0.0    False                3    5.0
6    w5ou        False   g8yot4nl        0.0    False                4    NaN
7    c3wp        False   sgqfg69a        0.0    False                5    NaN
8    v8jb        False   p3ptl9nz        0.0    False                3    5.0
9    w0wv        False   q9duu1ah        0.0    False                1    4.0

## Restructure datasets (rename, reformat and rearrange)

In [ ]:
# Restructure columns for analysis

# Columns from df_restos
df_restos['Reviewers'] = df_restos['Reviewers'].str.replace(r'[-()+\s]+', '', regex=True)

# Columns from df_reviews
# Rename columns
df_reviews = df_reviews.rename(columns={
    'likeCount': 'Likes',
    'restaurant_food': 'FoodRating',
    'rider': 'RiderRating'
})

# Change dtype of certain columns
df_reviews['FoodRating'] = df_reviews['FoodRating'].astype('float64')
df_restos['Reviewers'] = df_restos['Reviewers'].astype('int64')

# Rearrange columns
df_reviews = df_reviews[['StoreId', 'isAnonymous', 'reviewerId', 'isLiked', 'Likes', 'FoodRating', 'RiderRating']]

# Display both df info
print("First df : Restos")
print("-" * 50)
df_restos.info()
print("=" * 50 + "\n\n")

print("Second df : Reviews")
print("-" * 50)
df_reviews.info()
print("=" * 50)

First df : Restos
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5649 entries, 0 to 5648
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StoreId            5649 non-null   object
 1   CompleteStoreName  5649 non-null   object
 2   FoodType           5649 non-null   object
 3   AverageRating      5649 non-null   float64
 4   Reviewers          5649 non-null   int64
 5   City               5649 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 264.9+ KB
==================================================


Second df : Reviews
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76213 entries, 0 to 76212
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StoreId      76213 non-null  object
 1   isAnonymous  76213 non-null  bool
 2   reviewerId   76213 non-null  object
 3   isLiked      76213 non-null  bool
 4   Likes        76213 non-null  float64
 5   FoodRating   76213 non-null  float64
 6   RiderRating  29760 non-null  float64
dtypes: bool(2), float64(3), object(2)
memory usage: 3.1+ MB
==================================================

## Preview updated dataframe

In [ ]:
# Display first 10 rows for both df
print("First df : Restos")
display(df_restos.head(10))
print("=" * 100 + "\n\n")

print("Second df : Reviews")
display(df_reviews.head(10))
print("=" * 100)

First df : Restos

,StoreId,CompleteStoreName,FoodType,AverageRating,Reviewers,City
0,sos6,Teochew Hai Gang Fish Soup 潮州海港鱼汤 (Toa Payoh),Asian,4.0,1,Singapore
1,cc4y,Homtang Thai (Balestier Road),Thai,4.9,9,Singapore
2,sh3w,Xin Mei Xiang Zheng Zong Lor Mee 新美香正宗卤面 (Bale...,Noodles,4.4,100,Singapore
3,ih76,Soon Huat BBQ Seafood (Lorong 4 Toa Payoh),Seafood,4.3,100,Singapore
4,yrj9,BaliNice Mala Hotpot 八里香麻辣香锅 (Lorong 1 Toa Payoh),Snacks,4.2,89,Singapore
5,s1jq,Shi Kou Seafood (Balestier Road),Chinese,4.3,500,Singapore
6,c8dk,Tea Apothecary (Toa Payoh View),Bubble Tea,4.7,100,Singapore
7,x7gm,Xiao Lao Ban Xiang Guo 小老板香锅 (Balestier Road),Curry,4.1,100,Singapore
8,x2ku,Thai Tai 泰太 (Former Noodle ThaiThai),Thai,4.7,3000,Singapore
9,h6sj,Fire Rice (125 Toa Payoh Lorong),Fried Rice,4.9,13,Singapore

====================================================================================================


Second df : Reviews

  StoreId  isAnonymous reviewerId  isLiked  Likes  FoodRating  RiderRating
0    y7bj        False   sghsi8yy    False    0.0         1.0          5.0
1    fnna        False   b1avz0td    False    0.0         5.0          5.0
2    kfgv        False   r8oii2qv    False    0.0         1.0          NaN
3    y8nn        False   sgnuk7bx    False    0.0         1.0          NaN
4    zu87        False   p2zyj8px    False    0.0         5.0          NaN
5    zhaf        False   g1pav7ov    False    0.0         3.0          5.0
6    w5ou        False   g8yot4nl    False    0.0         4.0          NaN
7    c3wp        False   sgqfg69a    False    0.0         5.0          NaN
8    v8jb        False   p3ptl9nz    False    0.0         3.0          5.0
9    w0wv        False   q9duu1ah    False    0.0         1.0          4.0

====================================================================================================

## Check null values and duplicate records

In [ ]:
# For df_restos
print("First df : Restos")
print("-" * 50)

# Check for null values in each column
null_values_restos = df_restos.isnull().sum()
print("Count of null values in each column :")
print(null_values_restos)
print("*" * 50)

# Check for duplicate records
duplicate_rows_restos = df_restos.duplicated().sum()
print("Count of duplicate rows :")
print(duplicate_rows_restos)
print("=" * 50 + "\n\n")

# For df_reviews
print("Second df : Reviews")
print("-" * 50)

# Check for null values in each column
null_values_reviews = df_reviews.isnull().sum()
print("Count of null values in each column :")
print(null_values_reviews)
print("*" * 50)

# Check for duplicate records
duplicate_rows_reviews = df_reviews.duplicated().sum()
print("Count of duplicate rows :")
print(duplicate_rows_reviews)
print("=" * 50)

First df : Restos
--------------------------------------------------
Count of null values in each column :
StoreId              0
CompleteStoreName    0
FoodType             0
AverageRating        0
Reviewers            0
City                 0
dtype: int64
**************************************************
Count of duplicate rows :
0
==================================================


Second df : Reviews
--------------------------------------------------
Count of null values in each column :
StoreId            0
isAnonymous        0
reviewerId         0
isLiked            0
Likes              0
FoodRating         0
RiderRating    46453
dtype: int64
**************************************************
Count of duplicate rows :
7092
==================================================

## Review at duplicate records for confirmation

In [ ]:
try:
    from tabulate import tabulate
except ImportError:
    print("Installing tabulate...")
    !pip install tabulate
    from tabulate import tabulate

# Print information about duplicate records in df_reviews
print("Duplicate records in df_reviews : " + "\n")

# Find all duplicated rows (excluding the first occurrence) based on all columns
duplicates = df_reviews[df_reviews.duplicated(keep=False)]

# Group duplicates by their unique combinations
duplicate_groups = duplicates.groupby(list(duplicates.columns))

# Get the first 5 unique duplicate groups
unique_duplicates = list(duplicate_groups)[:5]

# Iterate over each unique duplicate group
for idx, (group_name, group_df) in enumerate(unique_duplicates):
    print(f"Unique Duplicate Group {idx + 1} :")
    print("-" * 30)

    # Find all indexes with this duplicate group
    duplicate_indexes = group_df.index.tolist()

    # Total count of similar records
    count_duplicates = len(duplicate_indexes)

    # Print details for Unique Duplicate Group
    print(f"Indexes of duplicates : {duplicate_indexes[:10]}")
    print(f"Total similar records found : {count_duplicates}")

    # Print the duplicate record values
    for index in duplicate_indexes:
        print(tabulate(df_reviews.loc[[index]], headers='keys', tablefmt='pretty'))

    # Separate each unique duplicate group with "=" * 110
    if idx < len(unique_duplicates):
        print("=" * 110)
    print("\n")

# Define ANSI escape sequences for red color and reset
red_alert = '\033[91m'  # Red color
reset = '\033[0m'       # Reset to default

# Print red alert message with circled number
print(f"{red_alert}!!! ALERT !!!{reset}")

# List back total count of unique duplicate groups
total_unique_duplicates = len(duplicate_groups)
print(f"Total count of unique duplicate groups : {total_unique_duplicates}")

Duplicate records in df_reviews :

Unique Duplicate Group 1 :
------------------------------
Indexes of duplicates : [6819, 8849, 28969]
Total similar records found : 3
+------+---------+-------------+------------+---------+-------+------------+-------------+
|      | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+------+---------+-------------+------------+---------+-------+------------+-------------+
| 6819 |  a0gk   |    False    |  sgw9ymo2  |  False  |  0.0  |    5.0     |     5.0     |
+------+---------+-------------+------------+---------+-------+------------+-------------+
+------+---------+-------------+------------+---------+-------+------------+-------------+
|      | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+------+---------+-------------+------------+---------+-------+------------+-------------+
| 8849 |  a0gk   |    False    |  sgw9ymo2  |  False  |  0.0  |    5.0     |     5.0     |
+------+---------+-------------+------------+---------+-------+------------+-------------+
+-------+---------+-------------+------------+---------+-------+------------+-------------+
|       | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
| 28969 |  a0gk   |    False    |  sgw9ymo2  |  False  |  0.0  |    5.0     |     5.0     |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
==============================================================================================================


Unique Duplicate Group 2 :
------------------------------
Indexes of duplicates : [20544, 39528]
Total similar records found : 2
+-------+---------+-------------+------------+---------+-------+------------+-------------+
|       | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
| 20544 |  a0gk   |    False    |  sgyah3qg  |  False  |  0.0  |    4.0     |     5.0     |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
+-------+---------+-------------+------------+---------+-------+------------+-------------+
|       | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
| 39528 |  a0gk   |    False    |  sgyah3qg  |  False  |  0.0  |    4.0     |     5.0     |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
==============================================================================================================


Unique Duplicate Group 3 :
------------------------------
Indexes of duplicates : [18076, 39655]
Total similar records found : 2
+-------+---------+-------------+------------+---------+-------+------------+-------------+
|       | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
| 18076 |  a0gk   |    False    |  sgyah3qg  |  False  |  0.0  |    5.0     |     5.0     |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
+-------+---------+-------------+------------+---------+-------+------------+-------------+
|       | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
| 39655 |  a0gk   |    False    |  sgyah3qg  |  False  |  0.0  |    5.0     |     5.0     |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
==============================================================================================================


Unique Duplicate Group 4 :
------------------------------
Indexes of duplicates : [2144, 39230, 42431, 64261]
Total similar records found : 4
+------+---------+-------------+------------+---------+-------+------------+-------------+
|      | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+------+---------+-------------+------------+---------+-------+------------+-------------+
| 2144 |  a0pb   |    False    |  sgbux9gk  |  False  |  0.0  |    2.0     |     1.0     |
+------+---------+-------------+------------+---------+-------+------------+-------------+
+-------+---------+-------------+------------+---------+-------+------------+-------------+
|       | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
| 39230 |  a0pb   |    False    |  sgbux9gk  |  False  |  0.0  |    2.0     |     1.0     |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
+-------+---------+-------------+------------+---------+-------+------------+-------------+
|       | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
| 42431 |  a0pb   |    False    |  sgbux9gk  |  False  |  0.0  |    2.0     |     1.0     |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
+-------+---------+-------------+------------+---------+-------+------------+-------------+
|       | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
| 64261 |  a0pb   |    False    |  sgbux9gk  |  False  |  0.0  |    2.0     |     1.0     |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
==============================================================================================================


Unique Duplicate Group 5 :
------------------------------
Indexes of duplicates : [44204, 50141]
Total similar records found : 2
+-------+---------+-------------+------------+---------+-------+------------+-------------+
|       | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
| 44204 |  a0pb   |    False    |  sgomsx3t  |  False  |  0.0  |    3.0     |     5.0     |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
+-------+---------+-------------+------------+---------+-------+------------+-------------+
|       | StoreId | isAnonymous | reviewerId | isLiked | Likes | FoodRating | RiderRating |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
| 50141 |  a0pb   |    False    |  sgomsx3t  |  False  |  0.0  |    3.0     |     5.0     |
+-------+---------+-------------+------------+---------+-------+------------+-------------+
==============================================================================================================


!!! ALERT !!!
Total count of unique duplicate groups : 3757

In [ ]:
# Display record at index 17506
print("Record at index 17506 :")
print(df_reviews.iloc[17506])
print("")

# Display record at index 64936
print("Record at index 64936 :")
print(df_reviews.iloc[64936])

Record at index 17506 :
StoreId            a939
isAnonymous       False
reviewerId     g1ipy8qo
isLiked           False
Likes               0.0
FoodRating          5.0
RiderRating         5.0
Name: 17506, dtype: object

Record at index 64936 :
StoreId            a939
isAnonymous       False
reviewerId     g1ipy8qo
isLiked           False
Likes               0.0
FoodRating          5.0
RiderRating         5.0
Name: 64936, dtype: object

## Remove null and duplicate records

In [ ]:
# Remove rows with null values and duplicates for df_restos
df_restos.dropna(inplace=True)
df_restos.drop_duplicates(inplace=True)
df_restos.reset_index(drop=True, inplace=True)

# Remove rows with null values and duplicates for df_reviews
df_reviews.dropna(inplace=True)
df_reviews.drop_duplicates(inplace=True)
df_reviews.reset_index(drop=True, inplace=True)

# For df_restos
print("First df : Restos")
print("-" * 50)

# Print the updated count of null values in each column
print("Updated count of null values in each column :")
print(df_restos.isnull().sum())
print("*" * 50)

# Print the updated count of duplicate rows
print("Updated count of duplicate rows :")
print(df_restos.duplicated().sum())
print("=" * 50 + "\n\n")

# For df_reviews
print("Second df : Reviews")
print("-" * 50)

# Print the updated count of null values in each column
print("Updated count of null values in each column :")
print(df_reviews.isnull().sum())
print("*" * 50)

# Print the updated count of duplicate rows
print("Updated count of duplicate rows :")
print(df_restos.duplicated().sum())
print("=" * 50)

First df : Restos
--------------------------------------------------
Updated count of null values in each column :
StoreId              0
CompleteStoreName    0
FoodType             0
AverageRating        0
Reviewers            0
City                 0
dtype: int64
**************************************************
Updated count of duplicate rows :
0
==================================================


Second df : Reviews
--------------------------------------------------
Updated count of null values in each column :
StoreId        0
isAnonymous    0
reviewerId     0
isLiked        0
Likes          0
FoodRating     0
RiderRating    0
dtype: int64
**************************************************
Updated count of duplicate rows :
0
==================================================

In [ ]:
# Get the set of column names for each DataFrame
columns_restos = set(df_restos.columns)
columns_reviews = set(df_reviews.columns)

# Find common columns
common_columns = columns_restos.intersection(columns_reviews)

# Print common columns in a single line
print(f"DataFrames can be integrated or joined using columns : {', '.join(sorted(common_columns))}")
print("*" * 100)

# Define function to map pandas data types to Hive data types
def map_to_hive_type(pandas_type):
    if pandas_type == 'int64' or pandas_type == 'int32':
        return 'INT'
    elif pandas_type == 'float64' or pandas_type == 'float32':
        return 'DOUBLE'
    elif pandas_type == 'object':
        return 'STRING'
    elif pandas_type == 'bool':
        return 'BOOLEAN'
    elif pandas_type == 'datetime64[ns]':
        return 'TIMESTAMP'
    elif pandas_type == 'datetime.date':
        return 'DATE'
    else:
        return 'UNIDENTIFIED'

# For df_restos
print("\nFor df_restos :")
print("-" *100)

# Print headers
print("\nHeaders :")
print(df_restos.columns.tolist())

# Print data types
print("\nData types :")
for col in df_restos.columns:
    hive_type = map_to_hive_type(df_restos[col].dtype.name)
    print(f"{col} : {hive_type}")

# For df_reviews
print("\nFor df_reviews :")
print("-" *100)

# Print headers
print("\nHeaders :")
print(df_reviews.columns.tolist())

# Print data types
print("\nData types :")
for col in df_reviews.columns:
    hive_type = map_to_hive_type(df_reviews[col].dtype.name)
    print(f"{col} : {hive_type}")

print("=" * 100)

DataFrames can be integrated or joined using columns : StoreId
****************************************************************************************************

For df_restos :
----------------------------------------------------------------------------------------------------

Headers :
['StoreId', 'CompleteStoreName', 'FoodType', 'AverageRating', 'Reviewers', 'City']

Data types :
StoreId : STRING
CompleteStoreName : STRING
FoodType : STRING
AverageRating : DOUBLE
Reviewers : INT
City : STRING

For df_reviews :
----------------------------------------------------------------------------------------------------

Headers :
['StoreId', 'isAnonymous', 'reviewerId', 'isLiked', 'Likes', 'FoodRating', 'RiderRating']

Data types :
StoreId : STRING
isAnonymous : BOOLEAN
reviewerId : STRING
isLiked : BOOLEAN
Likes : DOUBLE
FoodRating : DOUBLE
RiderRating : DOUBLE
====================================================================================================

## Save dataset to local

In [ ]:
# Define the files path to save the CSV files
output_file_path_restos = r'/content/drive/MyDrive/project_dataset/restaurant.csv'
output_file_path_reviews = r'/content/drive/MyDrive/project_dataset/review.csv'

# Save the cleaned DataFrame to a CSV file
df_restos.to_csv(output_file_path_restos, index=False)
df_reviews.to_csv(output_file_path_reviews, index=False)

# Confirmation message
print(f"DataFrames saved successfully to:\n1. {output_file_path_restos}\n2. {output_file_path_reviews}")

DataFrames saved successfully to:
1. /content/drive/MyDrive/project_dataset/restaurant.csv
2. /content/drive/MyDrive/project_dataset/review.csv